### ISSUE TITLE
Issue: I don't have one

### ISSUE THREAD

**Issue by ghost** [brickbots/HandiPi#1]
![download](https://user-images.githubusercontent.com/42880321/187078939-2dde5539-66d2-4909-9523-8156aab0dedc.jpeg)

I have a 3d printer to make the case parts. I would be comfortable possibly f-ing up my rpi4 and removing/replacing its components if it was at msrp. At around $200(cad) I can't justify it. I'll be making the attempt if the prices ever come down. this is an Awsome build and something I have been looking for a while now!

thank you!

**Comment by kloontim** [comment]
+1

**Comment by jreniel** [comment]
I wish I would be able get this off the shelf! Been dreaming about something like this for a looong time!

**Comment by brickbots** [comment]
Hi @sgtbane and Co!  

Thanks for the awesome 'issue' here :-)   The general lack of availability of Pi's and the danger of destroying one is definitely the largest stumbling block here....

I've been meaning to take some of my PCB design skills up a notch and experiment with getting boards fully built/populated by the fabricator.  If I had those skills, this project could be re-imagined as a compute module carrier with USB/HDMI/Audio + power management all on one board which the compute module plugs into.  It could probably be a bit thinner, easier to produce for sale, and much easier to build.

I'd also like to offer it with at least two keyboard layouts... 36% and something closer to a standard 60%.   

Wouldn't solve the problem of compute modules being almost impossible to get, but it would make the whole project much simpler and open up the possibility of a group by of some sort.  

For now, I'm happy to provide any advice I can.  Just let me know if anyone has questions and thanks so much for the awesome feedback!

**Comment by sp00ck** [comment]
How many days this device work on one charging?
Why this is fat?

**Comment by brickbots** [comment]
Hi @sp00ck !  It runs for about 4 hours with general terminal and light web browsing use.  That can be extended by turning off wifi/down screen brightness to 5 or 6 if you are just editing code and such.

The thickness is required to fit the stack of the screen, pisugar and RPI4.  Here's a cut-away showing the arrangement.  Note that the Pisugar is not visible here, but it fits between the screen and Pi, which is why the Pi seems to have a gap above it:  
<img width="1075" alt="Screen Shot 2022-08-30 at 10 28 42 AM" src="https://user-images.githubusercontent.com/11450005/187504156-b58dc079-d2e7-448e-8fcc-7d26d610ca70.png">

There space under the keyboard, to the left in this image, is where the batter is located and there is absolutely room for a larger one which could double the runtime, I've just not found need for it yet :-)

**Comment by sp00ck** [comment]
i no need device with small working time

**Comment by Mortuus-Medicus** [comment]
> ![download](https://user-images.githubusercontent.com/42880321/187078939-2dde5539-66d2-4909-9523-8156aab0dedc.jpeg)
> 
> I have a 3d printer to make the case parts. I would be comfortable possibly f-ing up my rpi4 and removing/replacing its components if it was at msrp. At around $200(cad) I can't justify it. I'll be making the attempt if the prices ever come down. this is an Awsome build and something I have been looking for a while now!
> 
> thank you!

This project is basically PocketCHIP but with Raspberry Pi. If the price is too high, maybe try looking into getting PocketCHIP in the secondary market, but do keep in mind that the company that made then is dead, so software for  device including its standalone CHIP are mostly just in the open source community now. That's where Raspberry Pi has a huge advantage! Still worth the look though.

I am surprised that PocketCHIP wasn't mentioned anywhere, since it's basically the same thing. I guess that's why people say we did twice.
