### ISSUE TITLE
how only two diodes?

### ISSUE THREAD

**Issue by HamBrick327** [brickbots/HandiPi#7]
I'm trying to learn some circuits myself, and I'm having trouble understanding how ghost inputs are prevented with only two diodes, also given how the schematic says every key has it's own diode. Thanks!

EDIT: I'm also not sure what the diodes are being used for, I think its USB D+ and D-, but I'm not very confident.

**Comment by brickbots** [comment]
Hello HamBrick!

Thank you for checking out the HandiPi and I hope it helps you in your learning.  The two diodes on the top of board are zener diodes which are used to limit the voltage on the USB data lines to 3.3 volts, rather than the 5 volts the microcontroller is using. 

The diodes for adding multi-key press capabilities to the keyboard are surface mounted on the back of the board under each switch.  You can see them as the little dark-grey components in the photo below:

![](https://raw.githubusercontent.com/brickbots/HandiPi/main/images/build/IMG_8155.jpeg)

I'm happy to answer any questions you might have and good luck on your electronics design journey!

**Comment by HamBrick327** [comment]
that makes a lot more sense. I don't know how I missed that looking at the kicad files. Thanks for the help!
